version: "2"
services:
  web:
    image: "amanpreet9391/parse-server"
    ports:
         -  "1337:1337"
  debug:
    image: "amanpreet9391/node-inspector"
    ports:
         -  "8080:8080"
         -  "5858:5858"
         -  "9229:9229"
  monitor:
    image: "grafana/grafana"
    ports:
         - "3000:3000"      
  server:
    image: "jenkins"
    ports:
         - "8081:8080"

 
